### PR TITLE
MNT: rerender

### LINKED ISSUE #9: @conda-forge-admin, please rerender
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #9.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #9

### CODE REVIEW

**Comment by jaimergp** [comment]
The macOS builds are failing in `main`. Let's see if this fixes it.

**Comment by jaimergp** [comment]
Ok, working now. Note [this line](https://github.com/rosalindfranklininstitute/RedLionfish/blob/140a3037cd149d4cdb6c03ee4f73202980a43bda/setup_for_condabuild.py#L25) is out of date, @perdigao1.

Also what's the difference between the two setup.py file variants? Just the requirements. Conda-build will invoke pip without requirements anyway, but if you want to do it dynamically, [you can check for `os.environ['CONDA_BUILD']`](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html) and define the list of reqs as needed.

**Comment by jaimergp** [comment]
That said, those changes are probably better off in a new release. I am going to merge this one to fix the errors in `main` and have all builds for all platforms.

**Comment by perdigao1** [comment]
> Ok, working now. Note [this line](https://github.com/rosalindfranklininstitute/RedLionfish/blob/140a3037cd149d4cdb6c03ee4f73202980a43bda/setup_for_condabuild.py#L25) is out of date, @perdigao1.
> 
> Also what's the difference between the two setup.py file variants? Just the requirements. Conda-build will invoke pip without requirements anyway, but if you want to do it dynamically, [you can check for `os.environ['CONDA_BUILD']`](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html) and define the list of reqs as needed.

Hi,

The line with the old version number appears to be an old version of the file / commit, because the latest version has the correct number

I can't remember exactly why I created two different setup.py. If I remember correctly, one of the dependencies (PyOpenCL) would not install via pip in windows as it would require compilation of binaries. This was not a problem with conda-forge. But now it is possible to install PyOpenCL as the wheel files for different architectures are now available. Maybe the different setup files are not needed anymore.

Before I started using conda-forge, I was creating conda builds locally (see folder /conda-recipe and windows script conda-create-package.bat) and these do use the /conda-recipe and this uses the setup_for_conda_build.py . In the past it was working correctly and avoided the issue with the PyOpenCL. The feedstock meta.yaml was written based in this. I understand, this may be a bit confusing, but I priority is to make sure it works, it would probably work now if I change to use setup.py only.

**Pull request merged**
